"""empty message

Revision ID: 31863d596749
Revises: 45f8d0c056a3
Create Date: 2025-07-05 11:35:47.387647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31863d596749'
down_revision = '45f8d0c056a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_char', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='user_id::integer')
        batch_op.drop_constraint('fav_char_user_id_key', type_='unique')
        batch_op.create_foreign_key('fk_fav_char_user_id', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_fav_char_char_id', 'characters', ['char_id'], ['id'])

    with op.batch_alter_table('fav_planets', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='user_id::integer')
        batch_op.drop_constraint('fav_planets_user_id_key', type_='unique')
        batch_op.create_foreign_key('fk_fav_planets_planet_id', 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key('fk_fav_planets_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('fav_starships', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False,
               postgresql_using='user_id::integer')
        batch_op.drop_constraint('fav_starships_user_id_key', type_='unique')
        batch_op.create_foreign_key('fk_fav_starships_starship_id', 'starships', ['starship_id'], ['id'])
        batch_op.create_foreign_key('fk_fav_starships_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fav_starships', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fav_starships_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_fav_starships_starship_id', type_='foreignkey')
        batch_op.create_unique_constraint('fav_starships_user_id_key', ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using='user_id::varchar')

    with op.batch_alter_table('fav_planets', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fav_planets_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_fav_planets_planet_id', type_='foreignkey')
        batch_op.create_unique_constraint('fav_planets_user_id_key', ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using='user_id::varchar')

    with op.batch_alter_table('fav_char', schema=None) as batch_op:
        batch_op.drop_constraint('fk_fav_char_user_id', type_='foreignkey')
        batch_op.drop_constraint('fk_fav_char_char_id', type_='foreignkey')
        batch_op.create_unique_constraint('fav_char_user_id_key', ['user_id'])
        batch_op.alter_column('user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               postgresql_using='user_id::varchar')

    # ### end Alembic commands ###